last_change = 2024-06-28T15:42:40.299919Z
addr = 0x9c00
size = 0xbc8

[stack_vars.-0x110]
last_change = 2024-06-28T15:42:40.267532Z
offset = -272
name = "a1"
type = "_QWORD[2]"
size = 0x10
addr = 0x9c00

[stack_vars.-0xb0]
last_change = 2024-06-28T15:42:40.273535Z
offset = -176
name = "var_A0"
type = "__int128[2]"
size = 0x20
addr = 0x9c00

[stack_vars.-0x90]
last_change = 2024-06-28T15:42:40.281002Z
offset = -144
name = "var_80"
type = "__int128[2]"
size = 0x20
addr = 0x9c00

[stack_vars.-0x70]
last_change = 2024-06-28T15:42:40.287011Z
offset = -112
name = "var_60"
type = "__int128[2]"
size = 0x20
addr = 0x9c00

[stack_vars.-0x50]
last_change = 2024-06-28T15:42:40.294016Z
offset = -80
name = "var_40"
type = "__int128[2]"
size = 0x20
addr = 0x9c00

[stack_vars.-0x30]
last_change = 2024-06-28T15:42:40.299919Z
offset = -48
name = "var_20"
type = "__int128[2]"
size = 0x20
addr = 0x9c00
