last_change = 2024-06-27T09:53:51.910447Z
addr = 0x9c00
size = 0xbc8

[stack_vars.-0xb0]
last_change = 2024-06-27T09:53:51.884518Z
offset = -176
name = "var_A0"
type = "__int128[2]"
size = 0x20
addr = 0x9c00

[stack_vars.-0x70]
last_change = 2024-06-27T09:53:51.910447Z
offset = -112
name = "var_60"
type = "__int128[2]"
size = 0x20
addr = 0x9c00
