last_change = 2024-06-28T15:42:40.720732Z
addr = 0x1e220
size = 0x154

[stack_vars.-0x58]
last_change = 2024-06-28T15:42:40.720732Z
offset = -88
name = "var_48"
type = "__int128"
size = 0x10
addr = 0x1e220
