last_change = 2024-06-28T15:42:42.462745Z
addr = 0x270a0
size = 0x14c

[stack_vars.-0x30]
last_change = 2024-06-28T15:42:42.462745Z
offset = -48
name = "var_30"
type = "__int128"
size = 0x10
addr = 0x270a0
