last_change = 2024-06-28T15:42:42.966290Z
addr = 0x27920
size = 0x14c

[stack_vars.-0x80]
last_change = 2024-06-28T15:42:42.966290Z
offset = -128
name = "a1"
type = "_QWORD[2]"
size = 0x10
addr = 0x27920
