last_change = 2024-06-28T15:42:41.517666Z
addr = 0x25d70
size = 0x14c

[stack_vars.-0x58]
last_change = 2024-06-28T15:42:41.517666Z
offset = -88
name = "var_58"
type = "__int128[2]"
size = 0x20
addr = 0x25d70
