last_change = 2024-06-28T15:42:42.528440Z
addr = 0x27740
size = 0x1d2

[stack_vars.-0x80]
last_change = 2024-06-28T15:42:42.503885Z
offset = -128
name = "var_70"
type = "__int128[2]"
size = 0x20
addr = 0x27740

[stack_vars.-0x58]
last_change = 2024-06-28T15:42:42.522420Z
offset = -88
name = "var_48"
type = "__int128"
size = 0x10
addr = 0x27740

[stack_vars.-0x30]
last_change = 2024-06-28T15:42:42.528440Z
offset = -48
name = "var_20"
type = "__int128[2]"
size = 0x20
addr = 0x27740
