last_change = 2024-06-28T15:42:41.490702Z
addr = 0x25ad0
size = 0x14c

[stack_vars.-0x30]
last_change = 2024-06-28T15:42:41.490702Z
offset = -48
name = "var_30"
type = "__int128"
size = 0x10
addr = 0x25ad0
