last_change = 2024-06-28T11:24:56.169105Z
addr = 0x24bf90
size = 0x17d

[stack_vars.-0x50]
last_change = 2024-06-28T11:24:56.169105Z
offset = -80
name = "var_30"
type = "long long[3]"
size = 0x18
addr = 0x24bf90
