last_change = 2024-06-28T11:24:56.169105Z
addr = 0x24a560
size = 0x14f

[stack_vars.-0x48]
last_change = 2024-06-28T11:24:56.169105Z
offset = -72
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x24a560
