last_change = 2024-06-28T11:24:56.171105Z
addr = 0x2cfea0
size = 0x248

[stack_vars.-0x68]
last_change = 2024-06-28T11:24:56.171105Z
offset = -104
name = "a1"
type = "long long[8]"
size = 0x40
addr = 0x2cfea0
