last_change = 2024-06-28T11:24:59.606561Z
addr = 0x445d00
size = 0x208

[stack_vars.-0x50]
last_change = 2024-06-28T11:24:59.606561Z
offset = -80
name = "var_38"
type = "long long[3]"
size = 0x18
addr = 0x445d00
