last_change = 2024-06-28T11:24:57.708783Z
addr = 0x440910
size = 0x1ab

[stack_vars.-0x30]
last_change = 2024-06-28T11:24:57.708783Z
offset = -48
name = "var_28"
type = "long long[3]"
size = 0x18
addr = 0x440910
