last_change = 2024-06-28T11:25:02.656850Z
addr = 0x47e680
size = 0x208

[stack_vars.-0x50]
last_change = 2024-06-28T11:25:02.656850Z
offset = -80
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x47e680
