last_change = 2024-06-28T11:24:59.611562Z
addr = 0x47e200
size = 0x208

[stack_vars.-0x50]
last_change = 2024-06-28T11:24:59.611562Z
offset = -80
name = "var_38"
type = "long long[3]"
size = 0x18
addr = 0x47e200
