last_change = 2024-06-28T11:25:02.662114Z
addr = 0x4f3a00
size = 0x1c5

[stack_vars.-0xb8]
last_change = 2024-06-28T11:25:02.662114Z
offset = -184
name = "var_98"
type = "long long[3]"
size = 0x18
addr = 0x4f3a00
