last_change = 2024-06-28T11:25:06.193923Z
addr = 0x6e9f80
size = 0x289

[stack_vars.-0x88]
last_change = 2024-06-28T11:25:06.193923Z
offset = -136
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x6e9f80
