last_change = 2024-06-28T11:25:06.205435Z
addr = 0x70bcf0
size = 0x208

[stack_vars.-0x50]
last_change = 2024-06-28T11:25:06.205435Z
offset = -80
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x70bcf0
