last_change = 2024-06-28T11:25:08.903016Z
addr = 0x721d30
size = 0x208

[stack_vars.-0x50]
last_change = 2024-06-28T11:25:08.903016Z
offset = -80
name = "var_38"
type = "long long[3]"
size = 0x18
addr = 0x721d30
