last_change = 2024-06-28T11:25:08.904017Z
addr = 0x847d10
size = 0x1503

[stack_vars.-0xd10]
last_change = 2024-06-28T11:25:08.904017Z
offset = -3344
name = "a1"
type = "long long[4]"
size = 0x20
addr = 0x847d10
