last_change = 2024-06-28T11:25:17.278845Z
addr = 0x8fbd40
size = 0x167

[stack_vars.-0x48]
last_change = 2024-06-28T11:25:17.278845Z
offset = -72
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x8fbd40
