last_change = 2024-06-27T13:15:54.889965Z
addr = 0x907a00
size = 0x189
name = "__ZNSt3__16__treeINS_12__value_typeI16ResourceLocation14BedrockTextureEENS_19__map_value_compareIS2_S4_NS_4lessIS2_EELb1EEENS_9allocatorIS4_EEE25__emplace_unique_key_argsIS2_JRKNS_21piecewise_construct_tENS_5tupleIJRKS2_EEENSG_IJEEEEEENS_4pairINS_15__tree_iteratorIS4_PNS_11__tree_nodeIS4_PvEElEEbEERKT_DpOT0_"

[header]
last_change = 2024-06-27T13:15:54.889965Z
name = "__ZNSt3__16__treeINS_12__value_typeI16ResourceLocation14BedrockTextureEENS_19__map_value_compareIS2_S4_NS_4lessIS2_EELb1EEENS_9allocatorIS4_EEE25__emplace_unique_key_argsIS2_JRKNS_21piecewise_construct_tENS_5tupleIJRKS2_EEENSG_IJEEEEEENS_4pairINS_15__tree_iteratorIS4_PNS_11__tree_nodeIS4_PvEElEEbEERKT_DpOT0_"
addr = 0x907a00

[header.args]
