last_change = 2024-06-27T13:16:50.578610Z
addr = 0x9078c0
size = 0x13c
name = "__ZNSt3__16__treeINS_12__value_typeI16ResourceLocationNS_8optionalIjEEEENS_19__map_value_compareIS2_S5_NS_4lessIS2_EELb1EEENS_9allocatorIS5_EEE25__emplace_unique_key_argsIS2_JRKNS_21piecewise_construct_tENS_5tupleIJRKS2_EEENSH_IJEEEEEENS_4pairINS_15__tree_iteratorIS5_PNS_11__tree_nodeIS5_PvEElEEbEERKT_DpOT0_"

[header]
last_change = 2024-06-27T13:16:50.578610Z
name = "__ZNSt3__16__treeINS_12__value_typeI16ResourceLocationNS_8optionalIjEEEENS_19__map_value_compareIS2_S5_NS_4lessIS2_EELb1EEENS_9allocatorIS5_EEE25__emplace_unique_key_argsIS2_JRKNS_21piecewise_construct_tENS_5tupleIJRKS2_EEENSH_IJEEEEEENS_4pairINS_15__tree_iteratorIS5_PNS_11__tree_nodeIS5_PvEElEEbEERKT_DpOT0_"
addr = 0x9078c0

[header.args]
