last_change = 2024-06-28T11:25:17.280847Z
addr = 0x915d10
size = 0x6e2

[stack_vars.-0xb0]
last_change = 2024-06-28T11:25:17.280847Z
offset = -176
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x915d10
