last_change = 2024-06-26T17:15:54.667638Z
addr = 0x9a0ee0
size = 0x1a3

[stack_vars.-0x198]
last_change = 2024-06-26T17:15:54.667638Z
offset = -408
name = "a4"
type = "long long[2]"
size = 0x10
addr = 0x9a0ee0
