last_change = 2024-06-28T11:25:17.279847Z
addr = 0x9c3570
size = 0x11e

[stack_vars.-0x58]
last_change = 2024-06-28T11:25:17.279847Z
offset = -88
name = "a1"
type = "long long"
size = 0x8
addr = 0x9c3570
