last_change = 2024-06-28T11:25:17.280847Z
addr = 0x9c3690
size = 0x105

[stack_vars.-0x58]
last_change = 2024-06-28T11:25:17.280847Z
offset = -88
name = "a1"
type = "long long"
size = 0x8
addr = 0x9c3690
