last_change = 2024-06-28T11:25:18.818560Z
addr = 0xab7ed0
size = 0x107

[stack_vars.-0x30]
last_change = 2024-06-28T11:25:18.818560Z
offset = -48
name = "var_28"
type = "long long[3]"
size = 0x18
addr = 0xab7ed0
