last_change = 2024-06-26T17:06:56.865173Z
addr = 0xacea60
size = 0xc0a

[stack_vars.-0x108]
last_change = 2024-06-26T17:06:56.865173Z
offset = -264
name = "a3"
type = "int[4]"
size = 0x10
addr = 0xacea60
