last_change = 2024-06-28T11:25:18.819559Z
addr = 0xae6820
size = 0x5d7

[stack_vars.-0x170]
last_change = 2024-06-28T11:25:18.819559Z
offset = -368
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0xae6820
