last_change = 2024-06-28T11:25:18.821062Z
addr = 0xb0cb80
size = 0x249

[stack_vars.-0x78]
last_change = 2024-06-28T11:25:18.821062Z
offset = -120
name = "a1"
type = "long long"
size = 0x8
addr = 0xb0cb80
