last_change = 2024-06-28T11:25:18.824071Z
addr = 0xb0dba0
size = 0x9e5

[stack_vars.-0x438]
last_change = 2024-06-28T11:25:18.824071Z
offset = -1080
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0xb0dba0
