last_change = 2024-06-28T11:25:21.732953Z
addr = 0xb116b0
size = 0x5fb

[stack_vars.-0x88]
last_change = 2024-06-28T11:25:21.732953Z
offset = -136
name = "var_60"
type = "long long[2]"
size = 0x10
addr = 0xb116b0
