last_change = 2024-06-28T11:25:22.950884Z
addr = 0xd52850
size = 0x243

[stack_vars.-0x89]
last_change = 2024-06-28T11:25:22.950884Z
offset = -137
name = "a1"
type = "long long"
size = 0x8
addr = 0xd52850
