last_change = 2024-06-28T11:25:22.951884Z
addr = 0xd834c0
size = 0x153

[stack_vars.-0x58]
last_change = 2024-06-28T11:25:22.951884Z
offset = -88
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0xd834c0
