last_change = 2024-06-26T17:15:54.666638Z
addr = 0xf01f90
size = 0x192

[stack_vars.-0x198]
last_change = 2024-06-26T17:15:54.666638Z
offset = -408
name = "var_170"
type = "__int128[2]"
size = 0x20
addr = 0xf01f90
