last_change = 2024-06-28T11:25:24.768907Z
addr = 0x10ffaa0
size = 0x254

[stack_vars.-0x91]
last_change = 2024-06-28T11:25:24.768907Z
offset = -145
name = "var_58"
type = "long long[4]"
size = 0x20
addr = 0x10ffaa0
