last_change = 2024-06-28T11:25:24.774412Z
addr = 0x114db00
size = 0x318

[stack_vars.-0xb0]
last_change = 2024-06-28T11:25:24.774412Z
offset = -176
name = "var_80"
type = "__m128i"
size = 0x10
addr = 0x114db00
