last_change = 2024-06-28T11:25:24.772906Z
addr = 0x114d2d0
size = 0x318

[stack_vars.-0xb0]
last_change = 2024-06-28T11:25:24.772906Z
offset = -176
name = "var_80"
type = "__m128i"
size = 0x10
addr = 0x114d2d0
