last_change = 2024-06-28T11:25:24.771907Z
addr = 0x1149820
size = 0x2f2

[stack_vars.-0x58]
last_change = 2024-06-28T11:25:24.771907Z
offset = -88
name = "a1"
type = "__m128i"
size = 0x10
addr = 0x1149820
