last_change = 2024-06-28T11:25:24.777423Z
addr = 0x1274240
size = 0x1f3

[stack_vars.-0x88]
last_change = 2024-06-28T11:25:24.777423Z
offset = -136
name = "a1"
type = "long long"
size = 0x8
addr = 0x1274240
