last_change = 2024-06-28T11:25:24.778423Z
addr = 0x12e6e60
size = 0x429

[stack_vars.-0x140]
last_change = 2024-06-28T11:25:24.778423Z
offset = -320
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x12e6e60
