last_change = 2024-06-28T11:25:24.778423Z
addr = 0x12e74b0
size = 0x373

[stack_vars.-0x58]
last_change = 2024-06-28T11:25:24.778423Z
offset = -88
name = "var_48"
type = "long long[3]"
size = 0x18
addr = 0x12e74b0
