last_change = 2024-06-28T11:25:26.871387Z
addr = 0x12f5bf0
size = 0x108

[stack_vars.-0x30]
last_change = 2024-06-28T11:25:26.871387Z
offset = -48
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x12f5bf0
