last_change = 2024-06-28T11:25:29.166148Z
addr = 0x13236c0
size = 0x4e4

[stack_vars.-0xd8]
last_change = 2024-06-28T11:25:29.166148Z
offset = -216
name = "var_B8"
type = "long long[2]"
size = 0x10
addr = 0x13236c0
