last_change = 2024-06-28T11:25:29.170147Z
addr = 0x1329b40
size = 0x5eb

[stack_vars.-0x198]
last_change = 2024-06-28T11:25:29.170147Z
offset = -408
name = "var_F8"
type = "long long[2]"
size = 0x10
addr = 0x1329b40
