last_change = 2024-06-26T17:15:54.670639Z
addr = 0x138e7a0
size = 0x6bd

[stack_vars.-0x5a0]
last_change = 2024-06-26T17:15:54.670639Z
offset = -1440
name = "a4"
type = "long long[40]"
size = 0x140
addr = 0x138e7a0
