last_change = 2024-06-26T17:15:54.670639Z
addr = 0x1399170
size = 0x7a2

[stack_vars.-0x538]
last_change = 2024-06-26T17:15:54.670639Z
offset = -1336
name = "a4"
type = "char[320]"
size = 0x140
addr = 0x1399170
