last_change = 2024-06-28T11:25:31.341494Z
addr = 0x1436380
size = 0x1f9

[stack_vars.-0x58]
last_change = 2024-06-28T11:25:31.341494Z
offset = -88
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x1436380
