last_change = 2024-06-28T11:25:29.169148Z
addr = 0x1434ca0
size = 0x94c

[stack_vars.-0x101]
last_change = 2024-06-28T11:25:29.169148Z
offset = -257
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x1434ca0
