last_change = 2024-06-28T11:25:31.350001Z
addr = 0x1546ef0
size = 0xae

[stack_vars.-0x30]
last_change = 2024-06-28T11:25:31.350001Z
offset = -48
name = "var_28"
type = "long long[3]"
size = 0x18
addr = 0x1546ef0
