last_change = 2024-06-28T11:25:31.349002Z
addr = 0x15520f0
size = 0x20b

[stack_vars.-0x80]
last_change = 2024-06-28T11:25:31.349002Z
offset = -128
name = "a1"
type = "long long"
size = 0x8
addr = 0x15520f0
