last_change = 2024-06-28T11:25:31.352002Z
addr = 0x157aa80
size = 0x30a

[stack_vars.-0x90]
last_change = 2024-06-28T11:25:31.352002Z
offset = -144
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x157aa80
