last_change = 2024-06-28T11:25:31.352002Z
addr = 0x158c490
size = 0x296

[stack_vars.-0xa0]
last_change = 2024-06-28T11:25:31.352002Z
offset = -160
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x158c490
