last_change = 2024-06-28T11:25:31.353002Z
addr = 0x15a87f0
size = 0x12b

[stack_vars.-0x58]
last_change = 2024-06-28T11:25:31.353002Z
offset = -88
name = "a1"
type = "long long[8]"
size = 0x40
addr = 0x15a87f0
