last_change = 2024-06-28T11:25:33.840194Z
addr = 0x15c81f0
size = 0x153

[stack_vars.-0x58]
last_change = 2024-06-28T11:25:33.840194Z
offset = -88
name = "var_58"
type = "long long[8]"
size = 0x40
addr = 0x15c81f0
