last_change = 2024-06-28T11:25:33.840194Z
addr = 0x15cb240
size = 0x11d

[stack_vars.-0xa4]
last_change = 2024-06-28T11:25:33.840194Z
offset = -164
name = "var_90"
type = "long long[4]"
size = 0x20
addr = 0x15cb240
