last_change = 2024-06-28T11:25:33.839194Z
addr = 0x1605050
size = 0x394

[stack_vars.-0x98]
last_change = 2024-06-28T11:25:33.839194Z
offset = -152
name = "var_48"
type = "long long[2]"
size = 0x10
addr = 0x1605050
