last_change = 2024-06-28T11:25:33.847239Z
addr = 0x16c32c0
size = 0x78

[stack_vars.-0x28]
last_change = 2024-06-28T11:25:33.847239Z
offset = -40
name = "var_28"
type = "long long[3]"
size = 0x18
addr = 0x16c32c0
