last_change = 2024-06-28T11:25:36.153334Z
addr = 0x1748c50
size = 0xf37

[stack_vars.-0x608]
last_change = 2024-06-28T11:25:36.153334Z
offset = -1544
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x1748c50
