last_change = 2024-06-28T11:25:36.153334Z
addr = 0x19aa990
size = 0x4fa

[stack_vars.-0x78]
last_change = 2024-06-28T11:25:36.153334Z
offset = -120
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x19aa990
