last_change = 2024-06-28T11:25:36.157334Z
addr = 0x1a77820
size = 0x157

[stack_vars.-0x58]
last_change = 2024-06-28T11:25:36.157334Z
offset = -88
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x1a77820
