last_change = 2024-06-28T11:25:36.160334Z
addr = 0x1a7ef70
size = 0x8f5

[stack_vars.-0xa8]
last_change = 2024-06-28T11:25:36.160334Z
offset = -168
name = "var_88"
type = "long long[3]"
size = 0x18
addr = 0x1a7ef70
