last_change = 2024-06-28T11:25:38.200929Z
addr = 0x1b2f6c0
size = 0x624

[stack_vars.-0x1f0]
last_change = 2024-06-28T11:25:38.200929Z
offset = -496
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x1b2f6c0
