last_change = 2024-06-28T11:25:38.207062Z
addr = 0x1b33920
size = 0x4f1

[stack_vars.-0x118]
last_change = 2024-06-28T11:25:38.207062Z
offset = -280
name = "var_F0"
type = "long long[2]"
size = 0x10
addr = 0x1b33920
