last_change = 2024-06-28T11:25:38.202930Z
addr = 0x1b302d0
size = 0x151

[stack_vars.-0xc0]
last_change = 2024-06-28T11:25:38.202930Z
offset = -192
name = "a1"
type = "long long"
size = 0x8
addr = 0x1b302d0
