last_change = 2024-06-28T11:25:38.202930Z
addr = 0x1b30430
size = 0x1ce

[stack_vars.-0x78]
last_change = 2024-06-28T11:25:38.202930Z
offset = -120
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x1b30430
