last_change = 2024-06-28T11:25:38.204062Z
addr = 0x1b31f50
size = 0x295

[stack_vars.-0xe8]
last_change = 2024-06-28T11:25:38.204062Z
offset = -232
name = "var_E0"
type = "long long[2]"
size = 0x10
addr = 0x1b31f50
