last_change = 2024-06-28T11:25:38.207062Z
addr = 0x1b367a0
size = 0x37e

[stack_vars.-0x128]
last_change = 2024-06-28T11:25:38.207062Z
offset = -296
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x1b367a0
