last_change = 2024-06-28T11:25:53.859880Z
addr = 0x1c0ba40
size = 0x522

[stack_vars.-0xd0]
last_change = 2024-06-28T11:25:53.859880Z
offset = -208
name = "a1"
type = "long long"
size = 0x8
addr = 0x1c0ba40
