last_change = 2024-06-28T11:25:53.865879Z
addr = 0x1ce91a0
size = 0x7ae

[stack_vars.-0x308]
last_change = 2024-06-28T11:25:53.865879Z
offset = -776
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x1ce91a0
