last_change = 2024-06-28T11:25:53.864879Z
addr = 0x1ce51c0
size = 0x32d

[stack_vars.-0xb8]
last_change = 2024-06-28T11:25:53.864879Z
offset = -184
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x1ce51c0
