last_change = 2024-06-28T11:25:55.444257Z
addr = 0x1cf4a50
size = 0x116

[stack_vars.-0xb8]
last_change = 2024-06-28T11:25:55.444257Z
offset = -184
name = "a1"
type = "long long"
size = 0x8
addr = 0x1cf4a50
