last_change = 2024-06-28T11:25:55.443251Z
addr = 0x1cf4820
size = 0x22c

[stack_vars.-0x120]
last_change = 2024-06-28T11:25:55.443251Z
offset = -288
name = "a1"
type = "long long"
size = 0x8
addr = 0x1cf4820
