last_change = 2024-06-28T11:25:55.439744Z
addr = 0x1cf3b50
size = 0x1a1

[stack_vars.-0x100]
last_change = 2024-06-28T11:25:55.439744Z
offset = -256
name = "var_F8"
type = "long long[3]"
size = 0x18
addr = 0x1cf3b50
