last_change = 2024-06-28T11:25:55.438741Z
addr = 0x1cf32b0
size = 0x341

[stack_vars.-0x208]
last_change = 2024-06-28T11:25:55.438741Z
offset = -520
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x1cf32b0
