last_change = 2024-06-28T11:25:57.294936Z
addr = 0x1cf5400
size = 0xfd

[stack_vars.-0xa0]
last_change = 2024-06-28T11:25:57.294936Z
offset = -160
name = "var_A0"
type = "long long"
size = 0x8
addr = 0x1cf5400
