last_change = 2024-06-28T11:25:59.063178Z
addr = 0x1e1b8b0
size = 0x74b

[stack_vars.-0x220]
last_change = 2024-06-28T11:25:59.063178Z
offset = -544
name = "var_1F0"
type = "long long[2]"
size = 0x10
addr = 0x1e1b8b0
