last_change = 2024-06-28T11:26:00.399217Z
addr = 0x1e2e070
size = 0x378

[stack_vars.-0x158]
last_change = 2024-06-28T11:26:00.399217Z
offset = -344
name = "var_130"
type = "long long[2]"
size = 0x10
addr = 0x1e2e070
