last_change = 2024-06-28T11:25:59.066178Z
addr = 0x1e24210
size = 0x11b

[stack_vars.-0x70]
last_change = 2024-06-28T11:25:59.066178Z
offset = -112
name = "var_58"
type = "long long[2]"
size = 0x10
addr = 0x1e24210
