last_change = 2024-06-28T11:25:59.071686Z
addr = 0x1e2c220
size = 0x11d

[stack_vars.-0xa8]
last_change = 2024-06-28T11:25:59.071686Z
offset = -168
name = "var_A8"
type = "long long"
size = 0x8
addr = 0x1e2c220
