last_change = 2024-06-28T11:26:00.400220Z
addr = 0x1e32590
size = 0x18b

[stack_vars.-0xc8]
last_change = 2024-06-28T11:26:00.400220Z
offset = -200
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x1e32590
