last_change = 2024-06-28T11:26:00.403220Z
addr = 0x1e376f0
size = 0xde

[stack_vars.-0x98]
last_change = 2024-06-28T11:26:00.403220Z
offset = -152
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x1e376f0
