last_change = 2024-06-28T11:26:00.406220Z
addr = 0x1e3cf50
size = 0x3fc

[stack_vars.-0x1c0]
last_change = 2024-06-28T11:26:00.406220Z
offset = -448
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x1e3cf50
