last_change = 2024-06-28T11:26:02.056427Z
addr = 0x1e44ef0
size = 0x43a

[stack_vars.-0x98]
last_change = 2024-06-28T11:26:02.056427Z
offset = -152
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x1e44ef0
