last_change = 2024-06-28T11:26:02.048976Z
addr = 0x1e43590
size = 0xfd

[stack_vars.-0x98]
last_change = 2024-06-28T11:26:02.048976Z
offset = -152
name = "a1"
type = "long long"
size = 0x8
addr = 0x1e43590
