last_change = 2024-06-28T11:26:02.043464Z
addr = 0x1e40f40
size = 0x14a

[stack_vars.-0xd0]
last_change = 2024-06-28T11:26:02.043464Z
offset = -208
name = "var_D0"
type = "long long"
size = 0x8
addr = 0x1e40f40
