last_change = 2024-06-28T11:26:02.051976Z
addr = 0x1e43d60
size = 0x10c

[stack_vars.-0xa0]
last_change = 2024-06-28T11:26:02.051976Z
offset = -160
name = "var_A0"
type = "long long"
size = 0x8
addr = 0x1e43d60
