last_change = 2024-06-28T11:26:02.054976Z
addr = 0x1e44410
size = 0x1c8

[stack_vars.-0xd0]
last_change = 2024-06-28T11:26:02.054976Z
offset = -208
name = "var_B0"
type = "long long"
size = 0x8
addr = 0x1e44410
