last_change = 2024-06-28T11:26:04.117114Z
addr = 0x2216b00
size = 0x58e

[stack_vars.-0x1d0]
last_change = 2024-06-28T11:26:04.117114Z
offset = -464
name = "a1"
type = "long long"
size = 0x8
addr = 0x2216b00
