last_change = 2024-06-28T11:26:04.118473Z
addr = 0x221fd10
size = 0xeb

[stack_vars.-0x98]
last_change = 2024-06-28T11:26:04.118473Z
offset = -152
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x221fd10
