last_change = 2024-06-28T11:26:04.120473Z
addr = 0x2224e20
size = 0x45c

[stack_vars.-0x128]
last_change = 2024-06-28T11:26:04.120473Z
offset = -296
name = "var_100"
type = "long long[3]"
size = 0x18
addr = 0x2224e20
