last_change = 2024-06-28T11:26:04.121473Z
addr = 0x2225550
size = 0x5d7

[stack_vars.-0x148]
last_change = 2024-06-28T11:26:04.121473Z
offset = -328
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x2225550
