last_change = 2024-06-28T11:26:04.119473Z
addr = 0x22212a0
size = 0x8bc

[stack_vars.-0x320]
last_change = 2024-06-28T11:26:04.119473Z
offset = -800
name = "var_2F0"
type = "long long[8]"
size = 0x40
addr = 0x22212a0
