last_change = 2024-06-28T11:26:07.935326Z
addr = 0x224c870
size = 0x43e

[stack_vars.-0x100]
last_change = 2024-06-28T11:26:07.935326Z
offset = -256
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x224c870
