last_change = 2024-06-28T11:26:07.933326Z
addr = 0x224aa80
size = 0x1de

[stack_vars.-0xc0]
last_change = 2024-06-28T11:26:07.933326Z
offset = -192
name = "var_A0"
type = "long long"
size = 0x8
addr = 0x224aa80
