last_change = 2024-06-28T11:26:07.935326Z
addr = 0x224adc0
size = 0x2e2

[stack_vars.-0x190]
last_change = 2024-06-28T11:26:07.935326Z
offset = -400
name = "var_168"
type = "long long[3]"
size = 0x18
addr = 0x224adc0
