last_change = 2024-06-28T11:26:05.923482Z
addr = 0x2243ce0
size = 0x273

[stack_vars.-0x68]
last_change = 2024-06-28T11:26:05.923482Z
offset = -104
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x2243ce0
