last_change = 2024-06-28T11:26:05.925988Z
addr = 0x2245460
size = 0x4a4

[stack_vars.-0x1b0]
last_change = 2024-06-28T11:26:05.925988Z
offset = -432
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x2245460
