last_change = 2024-06-28T11:26:05.927997Z
addr = 0x2247230
size = 0x36a

[stack_vars.-0x188]
last_change = 2024-06-28T11:26:05.927997Z
offset = -392
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x2247230
