last_change = 2024-06-28T11:26:07.936829Z
addr = 0x23ecfc0
size = 0x562

[stack_vars.-0x2d8]
last_change = 2024-06-28T11:26:07.936829Z
offset = -728
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x23ecfc0
