last_change = 2024-06-28T11:26:09.273697Z
addr = 0x23fd0b0
size = 0x1f3

[stack_vars.-0x120]
last_change = 2024-06-28T11:26:09.273697Z
offset = -288
name = "var_120"
type = "long long"
size = 0x8
addr = 0x23fd0b0
