last_change = 2024-06-28T11:26:07.940833Z
addr = 0x23f2600
size = 0x154

[stack_vars.-0xb0]
last_change = 2024-06-28T11:26:07.940833Z
offset = -176
name = "var_98"
type = "long long"
size = 0x8
addr = 0x23f2600
