last_change = 2024-06-28T11:26:07.942833Z
addr = 0x23f2380
size = 0x13a

[stack_vars.-0xb0]
last_change = 2024-06-28T11:26:07.942833Z
offset = -176
name = "a1"
type = "long long"
size = 0x8
addr = 0x23f2380
