last_change = 2024-06-28T11:26:10.920317Z
addr = 0x240ed50
size = 0x151

[stack_vars.-0xb0]
last_change = 2024-06-28T11:26:10.920317Z
offset = -176
name = "var_98"
type = "long long[3]"
size = 0x18
addr = 0x240ed50
