last_change = 2024-06-28T11:26:09.288889Z
addr = 0x240da90
size = 0x136

[stack_vars.-0xc8]
last_change = 2024-06-28T11:26:09.288889Z
offset = -200
name = "a1"
type = "long long"
size = 0x8
addr = 0x240da90
