last_change = 2024-06-28T11:26:09.286210Z
addr = 0x240ceb0
size = 0x136

[stack_vars.-0xc8]
last_change = 2024-06-28T11:26:09.286210Z
offset = -200
name = "var_B0"
type = "long long"
size = 0x8
addr = 0x240ceb0
