last_change = 2024-06-28T11:26:09.285210Z
addr = 0x240cff0
size = 0x170

[stack_vars.-0xd0]
last_change = 2024-06-28T11:26:09.285210Z
offset = -208
name = "var_B8"
type = "long long[2]"
size = 0x10
addr = 0x240cff0
