last_change = 2024-06-28T11:26:09.284210Z
addr = 0x240cc60
size = 0x12f

[stack_vars.-0xc0]
last_change = 2024-06-28T11:26:09.284210Z
offset = -192
name = "a1"
type = "long long"
size = 0x8
addr = 0x240cc60
