last_change = 2024-06-28T11:26:09.283210Z
addr = 0x240ca20
size = 0x12f

[stack_vars.-0xc0]
last_change = 2024-06-28T11:26:09.283210Z
offset = -192
name = "var_A0"
type = "long long"
size = 0x8
addr = 0x240ca20
