last_change = 2024-06-28T11:26:10.917311Z
addr = 0x240e890
size = 0x23d

[stack_vars.-0xd8]
last_change = 2024-06-28T11:26:10.917311Z
offset = -216
name = "a1"
type = "long long"
size = 0x8
addr = 0x240e890
