last_change = 2024-06-28T11:26:09.276699Z
addr = 0x24014f0
size = 0x183

[stack_vars.-0x50]
last_change = 2024-06-28T11:26:09.276699Z
offset = -80
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x24014f0
