last_change = 2024-06-28T11:26:10.925506Z
addr = 0x2412910
size = 0x1fa

[stack_vars.-0x58]
last_change = 2024-06-28T11:26:10.925506Z
offset = -88
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x2412910
