last_change = 2024-06-28T11:26:10.923312Z
addr = 0x24162c0
size = 0x1d0

[stack_vars.-0xc8]
last_change = 2024-06-28T11:26:10.923312Z
offset = -200
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x24162c0
