last_change = 2024-06-28T11:26:10.921313Z
addr = 0x2414f20
size = 0x1cc

[stack_vars.-0x78]
last_change = 2024-06-28T11:26:10.921313Z
offset = -120
name = "var_50"
type = "long long[2]"
size = 0x10
addr = 0x2414f20
