last_change = 2024-06-28T11:26:12.196280Z
addr = 0x24469d0
size = 0x143

[stack_vars.-0xc0]
last_change = 2024-06-28T11:26:12.196280Z
offset = -192
name = "var_A0"
type = "long long"
size = 0x8
addr = 0x24469d0
