last_change = 2024-06-28T11:26:10.928506Z
addr = 0x2445f60
size = 0x204

[stack_vars.-0xe0]
last_change = 2024-06-28T11:26:10.928506Z
offset = -224
name = "var_B8"
type = "long long[2]"
size = 0x10
addr = 0x2445f60
