last_change = 2024-06-28T11:26:12.201280Z
addr = 0x245c3f0
size = 0x143

[stack_vars.-0xc0]
last_change = 2024-06-28T11:26:12.201280Z
offset = -192
name = "a1"
type = "long long"
size = 0x8
addr = 0x245c3f0
