last_change = 2024-06-28T11:26:12.203280Z
addr = 0x24b53c0
size = 0x143

[stack_vars.-0xc0]
last_change = 2024-06-28T11:26:12.203280Z
offset = -192
name = "a1"
type = "long long"
size = 0x8
addr = 0x24b53c0
