last_change = 2024-06-28T11:26:12.205399Z
addr = 0x24fabf0
size = 0xf3

[stack_vars.-0xa0]
last_change = 2024-06-28T11:26:12.205399Z
offset = -160
name = "var_A0"
type = "long long"
size = 0x8
addr = 0x24fabf0
