last_change = 2024-06-28T11:26:17.378242Z
addr = 0x24fb630
size = 0xfa

[stack_vars.-0xb8]
last_change = 2024-06-28T11:26:17.378242Z
offset = -184
name = "a1"
type = "long long"
size = 0x8
addr = 0x24fb630
