last_change = 2024-06-28T11:26:17.379242Z
addr = 0x24fbe90
size = 0xfa

[stack_vars.-0xb8]
last_change = 2024-06-28T11:26:17.379242Z
offset = -184
name = "var_A0"
type = "long long"
size = 0x8
addr = 0x24fbe90
