last_change = 2024-06-28T11:26:17.382242Z
addr = 0x269ff30
size = 0x187c

[stack_vars.-0x228]
last_change = 2024-06-28T11:26:17.382242Z
offset = -552
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x269ff30
