last_change = 2024-06-28T11:26:17.383242Z
addr = 0x26ddf30
size = 0x187

[stack_vars.-0x68]
last_change = 2024-06-28T11:26:17.383242Z
offset = -104
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x26ddf30
