addr = 0x2737340
size = 0x1894
name = "__ZN6PlayerC2ER5LevelR12PacketSender8GameTypebRK17NetworkIdentifier11SubClientIdN3mce4UUIDERKNSt3__112basic_stringIcNSB_11char_traitsIcEENSB_9allocatorIcEEEESJ_NSB_10unique_ptrI11CertificateNSB_14default_deleteISL_EEEER13EntityContextSJ_SJ_"

[header]
last_change = 2024-06-27T23:46:33.990288Z
name = "__ZN6PlayerC2ER5LevelR12PacketSender8GameTypebRK17NetworkIdentifier11SubClientIdN3mce4UUIDERKNSt3__112basic_stringIcNSB_11char_traitsIcEENSB_9allocatorIcEEEESJ_NSB_10unique_ptrI11CertificateNSB_14default_deleteISL_EEEER13EntityContextSJ_SJ_"
addr = 0x2737340

[header.args]
