last_change = 2024-06-28T11:26:20.880679Z
addr = 0x277f3a0
size = 0x119

[stack_vars.-0x48]
last_change = 2024-06-28T11:26:20.880679Z
offset = -72
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x277f3a0
