last_change = 2024-06-28T11:26:20.882679Z
addr = 0x27b7dc0
size = 0x964

[stack_vars.-0x128]
last_change = 2024-06-28T11:26:20.882679Z
offset = -296
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x27b7dc0
