last_change = 2024-06-28T11:26:20.883679Z
addr = 0x2830c40
size = 0x319

[stack_vars.-0xc8]
last_change = 2024-06-28T11:26:20.883679Z
offset = -200
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x2830c40
