last_change = 2024-06-28T11:26:22.327039Z
addr = 0x293e4a0
size = 0x1ab

[stack_vars.-0x70]
last_change = 2024-06-28T11:26:22.327039Z
offset = -112
name = "var_50"
type = "long long[2]"
size = 0x10
addr = 0x293e4a0
