last_change = 2024-06-28T11:26:22.325039Z
addr = 0x293de60
size = 0x15d

[stack_vars.-0x78]
last_change = 2024-06-28T11:26:22.325039Z
offset = -120
name = "a1"
type = "long long"
size = 0x8
addr = 0x293de60
