last_change = 2024-06-28T11:26:25.020406Z
addr = 0x29b9c60
size = 0x110

[stack_vars.-0x58]
last_change = 2024-06-28T11:26:25.020406Z
offset = -88
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x29b9c60
