last_change = 2024-06-28T11:26:25.021406Z
addr = 0x29b9b50
size = 0x104

[stack_vars.-0x58]
last_change = 2024-06-28T11:26:25.021406Z
offset = -88
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x29b9b50
