last_change = 2024-06-28T11:26:25.022910Z
addr = 0x29ce930
size = 0x26a

[stack_vars.-0x68]
last_change = 2024-06-28T11:26:25.022910Z
offset = -104
name = "var_50"
type = "long long[3]"
size = 0x18
addr = 0x29ce930
