last_change = 2024-06-26T16:39:13.263792Z
addr = 0x29cd9a0
size = 0xaf
name = "?resetAttributes@Mob@@QEAAXXZ"

[header]
last_change = 2024-06-26T16:39:13.263792Z
name = "?resetAttributes@Mob@@QEAAXXZ"
addr = 0x29cd9a0

[header.args]
