last_change = 2024-06-28T11:26:25.025916Z
addr = 0x2a167c0
size = 0x98

[stack_vars.-0x28]
last_change = 2024-06-28T11:26:25.025916Z
offset = -40
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x2a167c0
