last_change = 2024-06-28T11:26:25.023915Z
addr = 0x2a14cd0
size = 0x1b0

[stack_vars.-0x48]
last_change = 2024-06-28T11:26:25.023915Z
offset = -72
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x2a14cd0
