last_change = 2024-06-28T11:26:25.025916Z
addr = 0x2a66570
size = 0xda4

[stack_vars.-0x28]
last_change = 2024-06-28T11:26:25.025916Z
offset = -40
name = "var_28"
type = "long long[3]"
size = 0x18
addr = 0x2a66570
