last_change = 2024-06-28T11:26:25.026917Z
addr = 0x2a8ec10
size = 0x211

[stack_vars.-0xb0]
last_change = 2024-06-28T11:26:25.026917Z
offset = -176
name = "a1"
type = "long long"
size = 0x8
addr = 0x2a8ec10
