addr = 0x2b318b0
size = 0x10
name = "?playerDimensionChangedEvent@PlayerDimensionTransferProxy@@UEAAXAEAVPlayer@@V?$AutomaticID@VDimension@@H@@1@Z"

[header]
last_change = 2024-06-26T17:11:07.334467Z
name = "?playerDimensionChangedEvent@PlayerDimensionTransferProxy@@UEAAXAEAVPlayer@@V?$AutomaticID@VDimension@@H@@1@Z"
addr = 0x2b318b0

[header.args]
