last_change = 2024-06-28T11:26:25.029916Z
addr = 0x2b61940
size = 0x3dd

[stack_vars.-0x140]
last_change = 2024-06-28T11:26:25.029916Z
offset = -320
name = "var_B0"
type = "long long[3]"
size = 0x18
addr = 0x2b61940
