last_change = 2024-06-28T11:26:48.338124Z
addr = 0x2e2b470
size = 0x956

[stack_vars.-0x1c0]
last_change = 2024-06-28T11:26:48.338124Z
offset = -448
name = "var_1B0"
type = "long long[2]"
size = 0x10
addr = 0x2e2b470
