last_change = 2024-06-28T11:26:49.858495Z
addr = 0x2f14b80
size = 0x1a2

[stack_vars.-0x48]
last_change = 2024-06-28T11:26:49.858495Z
offset = -72
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x2f14b80
