last_change = 2024-06-28T11:26:49.859495Z
addr = 0x2f158f0
size = 0x15d

[stack_vars.-0x48]
last_change = 2024-06-28T11:26:49.859495Z
offset = -72
name = "var_48"
type = "long long[3]"
size = 0x18
addr = 0x2f158f0
