last_change = 2024-06-28T11:26:49.860495Z
addr = 0x3229f20
size = 0x1e2

[stack_vars.-0x60]
last_change = 2024-06-28T11:26:49.860495Z
offset = -96
name = "var_58"
type = "long long[3]"
size = 0x18
addr = 0x3229f20
