last_change = 2024-06-28T11:26:49.861809Z
addr = 0x324c7e0
size = 0xe6

[stack_vars.-0x58]
last_change = 2024-06-28T11:26:49.861809Z
offset = -88
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x324c7e0
