last_change = 2024-06-28T11:26:49.866810Z
addr = 0x32f8100
size = 0xc3

[stack_vars.-0x48]
last_change = 2024-06-28T11:26:49.866810Z
offset = -72
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x32f8100
