last_change = 2024-06-28T11:26:53.397527Z
addr = 0x32fedf0
size = 0x13d

[stack_vars.-0x78]
last_change = 2024-06-28T11:26:53.397527Z
offset = -120
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x32fedf0
