last_change = 2024-06-28T11:26:53.402528Z
addr = 0x34a98b0
size = 0xbf3

[stack_vars.-0x1b8]
last_change = 2024-06-28T11:26:53.402528Z
offset = -440
name = "var_1B0"
type = "long long[2]"
size = 0x10
addr = 0x34a98b0
