last_change = 2024-06-28T11:26:53.399528Z
addr = 0x34a48f0
size = 0x16c

[stack_vars.-0x50]
last_change = 2024-06-28T11:26:53.399528Z
offset = -80
name = "var_30"
type = "long long[3]"
size = 0x18
addr = 0x34a48f0
