last_change = 2024-06-28T11:26:53.403527Z
addr = 0x359dd10
size = 0xa0b

[stack_vars.-0x240]
last_change = 2024-06-28T11:26:53.403527Z
offset = -576
name = "var_208"
type = "long long[2]"
size = 0x10
addr = 0x359dd10
