last_change = 2024-06-28T11:26:53.407566Z
addr = 0x362aa90
size = 0x253

[stack_vars.-0x98]
last_change = 2024-06-28T11:26:53.407566Z
offset = -152
name = "var_78"
type = "long long[2]"
size = 0x10
addr = 0x362aa90
