last_change = 2024-06-28T11:26:53.405527Z
addr = 0x3623230
size = 0x41f

[stack_vars.-0xe0]
last_change = 2024-06-28T11:26:53.405527Z
offset = -224
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x3623230
