last_change = 2024-06-26T17:15:54.675146Z
addr = 0x3859ba0
size = 0x99

[stack_vars.-0x168]
last_change = 2024-06-26T17:15:54.675146Z
offset = -360
name = "var_168"
type = "long long[4]"
size = 0x20
addr = 0x3859ba0
