last_change = 2024-06-28T11:26:54.312686Z
addr = 0x39c2080
size = 0x2b5

[stack_vars.-0x98]
last_change = 2024-06-28T11:26:54.312686Z
offset = -152
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x39c2080
