last_change = 2024-06-28T11:26:54.317190Z
addr = 0x3a37f70
size = 0x44f

[stack_vars.-0xa0]
last_change = 2024-06-28T11:26:54.317190Z
offset = -160
name = "var_80"
type = "long long[3]"
size = 0x18
addr = 0x3a37f70
