last_change = 2024-06-28T11:26:55.085710Z
addr = 0x3b15530
size = 0x262

[stack_vars.-0x190]
last_change = 2024-06-28T11:26:55.085710Z
offset = -400
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x3b15530
