last_change = 2024-06-28T11:26:55.090710Z
addr = 0x3b1a0c0
size = 0xb9

[stack_vars.-0x68]
last_change = 2024-06-28T11:26:55.090710Z
offset = -104
name = "a1"
type = "long long[2]"
size = 0x10
addr = 0x3b1a0c0
