last_change = 2024-06-28T11:26:59.768054Z
addr = 0x4188900
size = 0xcd

[stack_vars.-0x40]
last_change = 2024-06-28T11:26:59.768054Z
offset = -64
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x4188900
