last_change = 2024-06-28T11:26:59.771053Z
addr = 0x4280530
size = 0xd3

[stack_vars.-0x40]
last_change = 2024-06-28T11:26:59.771053Z
offset = -64
name = "a1"
type = "long long[3]"
size = 0x18
addr = 0x4280530
