user = "freddie"
version = "4.1.6"
last_push_time = 2024-07-08T16:52:02.074389Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Merged in <Function: None ?lookupByName@ItemRegistry@@AEBA?AV?$WeakPtr@VItem@@@@AEAHV?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z(args=0); @0x2b5ec50 vars=0 len=0x32a> from freddie"
