user = "tamaspapp"
version = "4.2.1"
last_push_time = 2024-06-26T16:37:48.665647Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Merged in <Function: long long * ?fireDimensionChangedEvent@Player@@QEAAXV?$AutomaticID@VDimension@@H@@0@Z(args=0); @0x2752960 vars=0 len=0x3be> from freddie"
