user = "freddie"
version = "4.1.6"
last_push_time = 2024-07-08T16:52:02.074389Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Merged in <Function: None ??$make_shared@VOverworldDimension@@AEAVILevel@@AEAVScheduler@@@std@@YA?AV?$shared_ptr@VOverworldDimension@@@0@AEAVILevel@@AEAVScheduler@@@Z(args=0); @0x409d000 vars=0 len=0x150> from freddie"
