user = "tamaspapp"
version = "4.2.1"
last_push_time = 2024-06-26T16:37:48.665647Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Merged in <Function: None ?fromTag@ItemStack@@SA?AV1@AEBVCompoundTag@@@Z(args=0); @0x2e0c0e0 vars=0 len=0x249> from freddie"
