user = "freddie"
version = "4.1.6"
last_push_time = 2024-07-08T21:31:07.095148Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Updated <FuncHeader: None ?getBiomeRegistry@Dimension@@UEBAAEBVBiomeRegistry@@XZ(args=0); @0x2fbd9e0>"
