user = "tamaspapp"
version = "4.2.1"
last_push_time = 2024-06-26T16:37:48.665647Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Merged in <Function: None ?getList@CompoundTag@@QEBAPEBVListTag@@V?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z(args=0); @0x1656120 vars=0 len=0x107> from freddie"
