user = "freddie"
version = "4.1.6"
last_push_time = 2024-07-08T16:52:02.074389Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Merged in <Function: void * ??$_Construct@$00PEBD@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAAXQEBD_K@Z(args=0); @0x145b40 vars=0 len=0xa5> from freddie"
