user = "freddie"
version = "4.1.6"
last_push_time = 2024-07-08T16:52:02.074389Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Merged in <Function: None ?playerDimensionChangedEvent@PlayerDimensionTransferProxy@@UEAAXAEAVPlayer@@V?$AutomaticID@VDimension@@H@@1@Z(args=0); @0x2b318b0 vars=0 len=0x10> from freddie"
